### ISSUE TITLE
Invoking LoAT on SAT instances

### ISSUE THREAD

**Issue by jena-kling** [LoAT-developers/LoAT#6]
Hey everyone
I am currently working with SMT-solvers and trying to get models for CHC-formulas. I saw in the last competition report of CHC-Comp that LoAT can now also handle SAT instances. However if I invoke `./loat-static --plain --proof-level 0 --mode reachability --format horn test.smt2` I constantly get `unknown` even for very simple and small SAT benchmarks from CHC-Comp s LIA-lin directory.
Am I doing something wrong?

Thanks in advance :)

**Comment by gruhn** [comment]
Hi, if I'm not mistaken this relates to work on the `transition-invariants` branch. I'm personally not involved but [here](https://github.com/LoAT-developers/LoAT/actions/runs/9795513178) you could download the latest built binary. And [here](https://github.com/LoAT-developers/LoAT/actions/runs/9795570353/job/27048047569) is the latest benchmark run for that branch. For example, it proved `sat` for `chc-LIA-Lin_060.smt2` from CHC-Comp 2023. Also looks like different command line arguments are needed:
```
./loat-static --mode safety --format horn --proof-level 0 --engine til --reverse "chc-LIA-Lin_060.smt2"
```
Not sure how stable this is at the moment. @ffrohn will know best, but I think he's on vacation right now.

**Comment by ffrohn** [comment]
Hi, with the version from the last competition, please use the additional command line argument --engine abmc. The default engine (adcl) can only prove unsat. However, even abmc is mainly for proving unsat, it's not competitive.

The work mentioned by Niklas is still under development and not yet well-tested.

**Comment by ffrohn** [comment]
Moreover, LoAT cannot yet produce models, unfortunately.

**Comment by jena-kling** [comment]
Ok thanks for explaining. Adding `--engine abmc` works just fine.
